/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package universidadnacional;

/**
 *
 * @author jps12
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dp = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuarch = new javax.swing.JMenu();
        menusalir = new javax.swing.JMenuItem();
        menupitag = new javax.swing.JMenu();
        Menucalcpitag = new javax.swing.JMenuItem();
        menuohm = new javax.swing.JMenu();
        menucalcvolt = new javax.swing.JMenuItem();
        menucalcCorr = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicación Unal");

        dp.setBackground(new java.awt.Color(149, 190, 252));

        javax.swing.GroupLayout dpLayout = new javax.swing.GroupLayout(dp);
        dp.setLayout(dpLayout);
        dpLayout.setHorizontalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        dpLayout.setVerticalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        menuarch.setText("Archivo");

        menusalir.setText("Salir");
        menusalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menusalirActionPerformed(evt);
            }
        });
        menuarch.add(menusalir);

        jMenuBar1.add(menuarch);

        menupitag.setText("Pitagoras");

        Menucalcpitag.setText("Calcular Pitagoras");
        Menucalcpitag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenucalcpitagActionPerformed(evt);
            }
        });
        menupitag.add(Menucalcpitag);

        jMenuBar1.add(menupitag);

        menuohm.setText("Ohm");

        menucalcvolt.setText("Calcular Voltage");
        menucalcvolt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucalcvoltActionPerformed(evt);
            }
        });
        menuohm.add(menucalcvolt);

        menucalcCorr.setText("Calcular Corriente");
        menucalcCorr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucalcCorrActionPerformed(evt);
            }
        });
        menuohm.add(menucalcCorr);

        jMenuBar1.add(menuohm);

        jMenu4.setText("Acerca");

        jMenuItem5.setText("Acerca de");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dp, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menusalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menusalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_menusalirActionPerformed

    private void MenucalcpitagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenucalcpitagActionPerformed
        // TODO add your handling code here:
        FrmPitagoras pitagoras = new FrmPitagoras();
        dp.add(pitagoras);
        pitagoras.setVisible(true);
        pitagoras.setClosable(true);
    }//GEN-LAST:event_MenucalcpitagActionPerformed

    private void menucalcvoltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucalcvoltActionPerformed
        // TODO add your handling code here:
        FrmVoltage voltage = new FrmVoltage();
        dp.add(voltage);
        voltage.setVisible(true);
        voltage.setClosable(true);
    }//GEN-LAST:event_menucalcvoltActionPerformed

    private void menucalcCorrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucalcCorrActionPerformed
        // TODO add your handling code here:
        FrmCorriente corriente = new FrmCorriente();
        dp.add(corriente);
        corriente.setVisible(true);
        corriente.setClosable(true);
    }//GEN-LAST:event_menucalcCorrActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        FrmAcercade acercade = new FrmAcercade();
        dp.add(acercade);
        acercade.setVisible(true);
        acercade.setClosable(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Menucalcpitag;
    private javax.swing.JDesktopPane dp;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenu menuarch;
    private javax.swing.JMenuItem menucalcCorr;
    private javax.swing.JMenuItem menucalcvolt;
    private javax.swing.JMenu menuohm;
    private javax.swing.JMenu menupitag;
    private javax.swing.JMenuItem menusalir;
    // End of variables declaration//GEN-END:variables
}
